---
title: "Exploratory"
author: "Matthew Johns"
date: "6/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plots

```{r echo=FALSE, include=FALSE}

library(tidyverse)
library(here)

here::here()

data <- read_csv(here("nuforc_reports.csv"))


data$primary_key <- 1:nrow(data)

data$sighting_year <- lubridate::year(data$date_time)



shape <- data %>% group_by(shape) %>% summarise(count = n()) %>% arrange(desc(count))

states <- data %>% group_by(state) %>% summarise(count = n()) %>% arrange(desc(count))


year <- data %>% group_by(sighting_year) %>% summarise(count = n()) #%>% arrange(desc(count))


```

```{r}
ggplot(shape, aes(x = reorder(shape, -count), y = count)) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .35))

ggplot(states, aes(x = reorder(state, -count), y = count)) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .35))


ggplot(year, aes(x = sighting_year, y = count)) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .35))

```

